<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="ModbusTCPReveal" Id="{eb92a042-d9e0-42c4-b278-20696ceefdc7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ModbusTCPReveal
VAR_INPUT
	IPAddress : STRING(15);
	modbusTCPPort : UINT := MODBUS_TCP_PORT;
	fbRead : FB_MBReadRegs;
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>